# example netlify.toml
[build]
  command = "npm run build"
  port = "functions"
  publish = "/build"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app. 
  ## Not needed for static site generators.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
  [production] 
    command = "node start" # Command to start your dev server
    port = 8080 # Port that the dev server will be listening on
    publish = "/build" # Folder with the static content for _redirect file
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
